import asyncio
from nexsus.utils.logger import Logger

class WAFDetector:
    def __init__(self, http_client):
        self.http_client = http_client
        self.logger = Logger("WAFDetector")
        self.waf_signatures = {
            'cloudflare': {
                'headers': ['cf-ray', 'cf-cache-status', 'cf-request-id'],
                'cookies': ['__cfduid', '__cf_bm'],
                'block_page': ['cloudflare', 'cf-error-code', 'cf-challenge', 'attention required'],
                'status_codes': [403, 503]
            },
            'akamai': {
                'headers': ['x-akamai-transformed', 'x-akamai-request-id'],
                'cookies': ['_abck', 'bm_sz', 'ak_bmsc'],
                'block_page': ['akamai', 'reference #', 'access denied'],
                'status_codes': [403, 401]
            },
            'aws_waf': {
                'headers': ['x-amzn-requestid', 'x-amzn-errortype'],
                'cookies': ['aws-waf-token'],
                'block_page': ['aws waf', 'request blocked', 'waf'],
                'status_codes': [403]
            },
            'azure_waf': {
                'headers': ['x-ms-request-id'],
                'cookies': ['azurewebapp'],
                'block_page': ['azure waf', 'application gateway'],
                'status_codes': [403, 404]
            },
            'modsecurity': {
                'headers': [],
                'cookies': [],
                'block_page': ['modsecurity', 'this error was generated by mod_security', 'mod_security'],
                'status_codes': [403, 406, 500]
            },
            'f5_bigip': {
                'headers': ['x-iinfo', 'bigipserver'],
                'cookies': ['ts', 'bigipserver', 'f5'],
                'block_page': ['f5', 'big-ip', 'the requested url was rejected'],
                'status_codes': [403, 500]
            },
            'imperva': {
                'headers': ['x-iinfo'],
                'cookies': ['incap_ses', 'visid_incap'],
                'block_page': ['incapsula', 'imperva', 'blocked because of malicious activity'],
                'status_codes': [403]
            },
            'sucuri': {
                'headers': ['x-sucuri-id', 'x-sucuri-cache'],
                'cookies': ['sucuri_cloudproxy'],
                'block_page': ['sucuri', 'cloudproxy'],
                'status_codes': [403]
            }
        }

    async def detect(self, url):
        self.logger.info(f"Fingerprinting WAF for {url}...")
        resp = await self.http_client.request('GET', url)
        if not resp:
            self.logger.warning("No response, cannot detect WAF")
            return None

        headers = {k.lower(): v for k, v in resp.headers.items()}
        content = ''
        try:
            content = (await resp.text()).lower()
        except:
            pass

        detected = []
        for waf, sig in self.waf_signatures.items():
            score = 0
            for h in sig['headers']:
                if h in headers:
                    score += 2
            set_cookie = headers.get('set-cookie', '').lower()
            for c in sig['cookies']:
                if c in set_cookie:
                    score += 2
            for bp in sig['block_page']:
                if bp in content:
                    score += 3
            if resp.status in sig['status_codes']:
                score += 1
            if score >= 3:
                detected.append((waf, score))

        if detected:
            detected.sort(key=lambda x: x[1], reverse=True)
            self.logger.success(f"Detected WAF: {detected[0][0]} (confidence {detected[0][1]})")
            return detected[0][0]
        self.logger.info("No WAF detected")
        return None
